#!/bin/bash
# Prepares Firebase + Google Sign-In configuration for building OurMoney.
#
# Usage: prepare_config.sh [plist_b64] [api_key] [gcm_sender_id] [project_id] [storage_bucket] [app_id] [gemini_key]
#
# Priority:
#   1. Base64-encoded full GoogleService-Info.plist (FIREBASE_PLIST_B64) — recommended.
#   2. Individual values (FIREBASE_API_KEY, GCM_SENDER_ID, FIREBASE_PROJECT_ID,
#      FIREBASE_STORAGE_BUCKET, FIREBASE_APP_ID) — a valid plist is generated from them.
#   3. A real plist already present in the working tree — used as-is.
#   4. Nothing supplied — a placeholder plist is written so the build still
#      compiles; Firebase will fail at runtime until a real config is provided.
#
# In every case Config/GoogleSignIn.xcconfig is generated with the
# GOOGLE_CLIENT_ID / REVERSED_CLIENT_ID needed by Google Sign-In.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PLIST_B64="${1:-${FIREBASE_PLIST_B64:-}}"
API_KEY="${2:-${FIREBASE_API_KEY:-}}"
SENDER_ID="${3:-${GCM_SENDER_ID:-}}"
PROJECT_ID="${4:-${FIREBASE_PROJECT_ID:-}}"
STORAGE_BUCKET="${5:-${FIREBASE_STORAGE_BUCKET:-}}"
APP_ID="${6:-${FIREBASE_APP_ID:-}}"
GEMINI_KEY="${7:-${GEMINI_API_KEY:-}}"

PLIST="OurMoney/GoogleService-Info.plist"

gen_xcconfig() {
  local client_id reversed
  client_id="$(/usr/libexec/PlistBuddy -c 'Print :CLIENT_ID' "$PLIST" 2>/dev/null || true)"
  reversed="$(/usr/libexec/PlistBuddy -c 'Print :REVERSED_CLIENT_ID' "$PLIST" 2>/dev/null || true)"
  cat > Config/GoogleSignIn.xcconfig <<EOF
// Generated by Scripts/prepare_config.sh — do not edit by hand.
GOOGLE_CLIENT_ID = ${client_id}
REVERSED_CLIENT_ID = ${reversed}
EOF
}

gen_placeholder_plist() {
  cat > "$PLIST" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>API_KEY</key><string>PLACEHOLDER</string>
  <key>GCM_SENDER_ID</key><string>000000000000</string>
  <key>PROJECT_ID</key><string>ourmoney-placeholder</string>
  <key>STORAGE_BUCKET</key><string>ourmoney-placeholder.appspot.com</string>
  <key>BUNDLE_ID</key><string>com.ourmoney.app</string>
  <key>CLIENT_ID</key><string></string>
  <key>REVERSED_CLIENT_ID</key><string></string>
  <key>PLIST_VERSION</key><string>1</string>
</dict>
</plist>
EOF
}

if [[ -n "$PLIST_B64" ]]; then
  echo "$PLIST_B64" | base64 --decode > "$PLIST"
  echo "Wrote GoogleService-Info.plist from FIREBASE_PLIST_B64."
elif [[ -n "$API_KEY" && -n "$SENDER_ID" && -n "$PROJECT_ID" && -n "$APP_ID" ]]; then
  BUNDLE_ID="com.ourmoney.app"
  [[ -z "$STORAGE_BUCKET" ]] && STORAGE_BUCKET="${PROJECT_ID}.appspot.com"
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>API_KEY</key><string>${API_KEY}</string>
  <key>GCM_SENDER_ID</key><string>${SENDER_ID}</string>
  <key>PROJECT_ID</key><string>${PROJECT_ID}</string>
  <key>STORAGE_BUCKET</key><string>${STORAGE_BUCKET}</string>
  <key>BUNDLE_ID</key><string>${BUNDLE_ID}</string>
  <key>GOOGLE_APP_ID</key><string>${APP_ID}</string>
  <key>CLIENT_ID</key><string></string>
  <key>REVERSED_CLIENT_ID</key><string></string>
  <key>PLIST_VERSION</key><string>1</string>
</dict>
</plist>
EOF
  echo "Wrote GoogleService-Info.plist from individual FIREBASE_* values."
elif [[ -f "$PLIST" ]] && ! grep -q 'PLACEHOLDER' "$PLIST" 2>/dev/null; then
  echo "Using existing GoogleService-Info.plist from the working tree."
else
  gen_placeholder_plist
  echo "WARNING: no Firebase configuration supplied; wrote a placeholder plist."
  echo "         Firebase auth/firestore will not work at runtime until the"
  echo "         real config is provided (see README: Firebase setup)."
fi

gen_xcconfig

if [[ -n "$GEMINI_KEY" ]]; then
  cat > Config/Secrets.xcconfig <<EOF
#include "GoogleSignIn.xcconfig"
GEMINI_API_KEY = ${GEMINI_KEY}
EOF
  echo "Wrote Config/Secrets.xcconfig with GEMINI_API_KEY."
fi

echo "Firebase configuration prepared."
